[tool.black]
line-length = 88
target-version = ['py312']
exclude = '''
/(
    migrations
|   venv
)/
'''

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88
exclude = .venv,venv,migrations
