name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create ZIP package (exclude venv and unnecessary files)
        run: |
          zip -r release.zip . \
            -x "venv/*" \
               "*.git*" \
               "*__pycache__*" \
               "*.pyc" \
               "*.pyo" \
               "release.zip" \
               ".github/*"

      - name: Deploy to Azure Web App (zip deploy)
        uses: azure/webapps-deploy@v2
        with:
          app-name: kpn-news-app
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: release.zip
